name: cache_manager_plus_utils
description: Utility package for cache manager plus.
version: 1.0.1
homepage: https://github.com/CoderNamedHendrick/cache_manager_utils
repository: https://github.com/CoderNamedHendrick/cache_manager_utils
issue_tracker: https://github.com/CoderNamedHendrick/cache_manager_utils/issues

topics:
  - cache-manager-plus
  - cache-manager-utils
  - caching

environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  cache_manager_plus: ^1.0.2
  hive_ce: ^2.11.1

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15
