name: CI pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  flutter_version: 3.29.3

jobs:
  run-tests-and-upload-coverage-report:
    name: Test package
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          cache: true
          flutter-version: '3.29.3'
          channel: 'stable'

      - name: Install dependencies
        run: dart pub get

      - run: dart pub global activate coverage
        name: Activate dart coverage

      - name: Format code
        run: dart format . --set-exit-if-changed

      - name: Lint analysis
        run: dart analyze

      - name: Run tests and generate coverage
        run: |
          dart run --define=CI_TEST=true test --use-data-isolate-strategy --coverage=./coverage
          dart pub global run coverage:format_coverage --packages=.dart_tool/package_config.json --report-on=lib --lcov -o ./coverage/lcov.info -i ./coverage
          rm -rf coverage/test
          rm -rf /Users/runner/work/cache_manager/CacheManagerPlusTest

      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}